### ISSUE TITLE
Add support for text styling

### ISSUE THREAD

**Issue by wolfcro1984** [halilozercan/ProgressButton#2]
In the constructor you can pass only the string value for the text widget which is created in normal button state.
```
val progressButton = ProgressButton(
    onPressed: VoidCallback,
    **text: "Login",**
    buttonState: ButtonState.normal,
    pBackgroundColor: Theme.of(context).primaryColor,
    pTextColor: Theme.of(context).primaryTextTheme.button.color,
    pProgressColor: Theme.of(context).primaryColor,
);
```
The problem is that this doesn't support styling the text.
Maybe even a better approach would be to allow a widget to be passed in for normal button state.

**Comment by halilozercan** [comment]
I think you are right. This was an early implementation to help myself learn flutter and I was mostly following my mobile experience from Android development. That's why I decided to have an easy implementation that gets you to jump start. However, it is pretty common and encouraged to pass child widgets in flutter as I understand.
